title: Seth Arreola # your name (or website title) here
logo: "/images/IMG_0809.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  M.S. Statistics Portfolio 
  <br><br>
  <a href="https://www.linkedin.com/in/seth-arreola-843113204/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
#theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
